version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000 # Storage
      - 9001:9001 # Console
    env_file:
      - ./.env
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/policies:/policies
    entrypoint: []
    command: >
      sh -c "cp -r /policies/* /data/.minio.sys/;
      minio server /data --console-address :9001;"

volumes:
  mysql_data:
    driver: local
